In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4,5]

In [3]:
array1=np.array(list1)
array1

array([1, 2, 3, 4, 5])

In [4]:
list2=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
array2=np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
array3=np.arange(1,18,2)
array3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [15]:
array3.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [18]:
array4=np.random.randint(1,10,10)
array4

array([1, 6, 7, 2, 9, 7, 7, 2, 1, 4])

In [29]:
array5=np.arange(1,6,1)
array5

array([1, 2, 3, 4, 5])

In [30]:
array5.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [31]:
array5.shape

(5,)

In [33]:
array6=np.arange(10)
array6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
array6[3]

3

In [35]:
array6[4]

4

In [36]:
array6[9]

9

In [41]:
for i in array6:
    if i%2==0:
        print(i)

0
2
4
6
8


In [47]:
for i in range(7,10):
    array6[i]=100

In [48]:
array6

array([  0,   1,   2,   3,   4,   5,   6, 100, 100, 100])

In [58]:
array7=np.arange(25)

In [62]:
array7=array7.reshape(5,5)

In [63]:
array7.shape

(5, 5)

In [64]:
array7[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])